title: "Team Fortress 2 Community Discord Wiki"
description: "The TF2 Community Discord's community-created wiki!"
url: "https://wiki.tf2.community/"
logo: /assets/icons/logo.svg
remote_theme: just-the-docs/just-the-docs
footer_content: "&copy; Team Fortress 2 Community - licensed under <a href=\"https://github.com/TF2CommunityDiscord/TF2CommunityDiscord.github.io/blob/main/LICENSE\">MIT</a>"
color_scheme: light

nav_footer_custom: "test"

aux_links:
  "Join the Discord server!":
    - "https://discord.gg/tf2"

plugins:
  - jekyll-seo-tag