title: Team Fortress 2 Community Wiki
logo: /assets/icons/logo.svg
remote_theme: mmistakes/jekyll-theme-basically-basic@1.4.5
copyright: "© Team Fortress 2 Community - licensed under [MIT](https://github.com/TF2CommunityDiscord/TF2CommunityDiscord.github.io/blob/main/LICENSE)"

sass:
  load_paths:
    - assets/stylesheets